// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gir.net.Infrastructure.Data;

#nullable disable

namespace gir.net.Infrastructure.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20260703215427_AddUserWarnPoints")]
    partial class AddUserWarnPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gir.net.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("Lifted")
                        .HasColumnType("boolean")
                        .HasColumnName("lifted");

                    b.Property<decimal?>("LiftedById")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("lifted_by_id");

                    b.Property<string>("LiftedByTag")
                        .HasColumnType("text")
                        .HasColumnName("lifted_by_tag");

                    b.Property<DateTime?>("LiftedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lifted_date");

                    b.Property<string>("LiftedReason")
                        .HasColumnType("text")
                        .HasColumnName("lifted_reason");

                    b.Property<decimal>("ModId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("mod_id");

                    b.Property<string>("ModTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mod_tag");

                    b.Property<string>("Punishment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("punishment");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cases_user_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("gir.net.Domain.Entities.FilterWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BypassLevel")
                        .HasColumnType("integer")
                        .HasColumnName("bypass_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FalsePositive")
                        .HasColumnType("boolean")
                        .HasColumnName("false_positive");

                    b.Property<bool>("Notify")
                        .HasColumnType("boolean")
                        .HasColumnName("notify");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phrase");

                    b.Property<bool>("PiracyWord")
                        .HasColumnType("boolean")
                        .HasColumnName("piracy_word");

                    b.Property<bool>("SilentFilter")
                        .HasColumnType("boolean")
                        .HasColumnName("silent_filter");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_filter_words");

                    b.HasIndex("Phrase")
                        .IsUnique()
                        .HasDatabaseName("ix_filter_words_phrase");

                    b.ToTable("filter_words", (string)null);
                });

            modelBuilder.Entity("gir.net.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AddedById")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by_id");

                    b.Property<string>("AddedByTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("added_by_tag");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("gir.net.Domain.Entities.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<int>("WarnPoints")
                        .HasColumnType("integer")
                        .HasColumnName("warn_points");

                    b.Property<bool>("WasWarnKicked")
                        .HasColumnType("boolean")
                        .HasColumnName("was_warn_kicked");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
