using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace gir.net.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MakeUserIdulong : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS;");

            migrationBuilder.AlterColumn<decimal>(
                name: "id",
                table: "users",
                type: "numeric(20,0)",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<long>(
                name: "id",
                table: "users",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric(20,0)");

            migrationBuilder.Sql(
                "ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;");
        }
    }
}
